FORMAT: 1A
HOST: http://ggmate.me/api

# GGMate

The GGMate API allows making requests for data on video game companies, people,
and the games they develop/publish.

# Group Companies
## Company List [/companies/{page}]
+ Parameters
    + page (number) - An optional page number, default is 1

### Obtain a list of companies. [GET]
+ Response 200 (application/json)

        {
            "companies": [
                {
                    "city": "Redwood City",
                    "country": "USA",
                    "date_founded": "Fri, 28 May 1982 00:00:00 GMT",
                    "deck": "EA is one of the largest publisher/developers in the video game industry.",
                    "id": 1,
                    "image": "http://static.giantbomb.com/uploads/scale_medium/0/4/9801-ea.jpg",
                    "name": "Electronic Arts"
                },
                {
                    "city": "Kita-ku Osaka-shi, Osaka",
                    "country": "Japan",
                    "date_founded": "Mon, 03 Apr 1995 00:00:00 GMT",
                    "deck": "Konami Computer Entertainment Osaka (KCEO) was founded April 3, 1995 as a subsidiary of Konami Corporation.  On March 1, 2003, KCEO's 139 employees were absorbed into a new branch, Konami Studios.  This new branch was later absorbed into the parent company in April 2005.",
                    "id": 2,
                    "image": "http://static.giantbomb.com/uploads/scale_medium/0/1992/1302163-kceo.jpeg",
                    "name": "Konami Computer Entertainment Osaka Co., Ltd."
                },
                {
                    "city": "St. Catharines",
                    "country": "Canada",
                    "date_founded": "Wed, 01 Jul 1992 00:00:00 GMT",
                    "deck": "Started by Denis Dyack in 1992, Silicon Knights are known for creating games with compelling and detailed mythologies.",
                    "id": 3,
                    "image": "http://static.giantbomb.com/uploads/scale_medium/0/26/11805-silicon_knights_logo_black.jpg",
                    "name": "Silicon Knights, Inc."
                }
            ]
        }

## Company [/companies/{company_id}]
+ Parameters
    + company_id (number) - ID of the company in the form of an integer

### Get the details of a specific company. [GET]
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Bioware",
            "deck": "BioWare is a game company that is currently owned by Electronic Arts (EA). It specializes in making role playing games that usually involve deep and engaging stories.",
            "date_founded": "1995-02-01 00:00:00",
            "city": "Edmonton",
            "country": "Canada",
            "website": "http://www.bioware.com",
            "image": "http://ggmate.me/static/company_banners/bioware.png",
            "games_developed": [
                {
                    "id": 23,
                    "name": "Baldur's Gate"
                },
                {
                    "id": 24,
                    "name": "Star Wars: Knights of the Old Republic"
                },
                {
                    "id": 25,
                    "name": "Mass Effect 2"
                }
            ],
            "games_published": [
                {
                    "id": 25,
                    "name": "Dragon Age Legends"
                }
            ]
        }

# Group People

## People List [/people/{page}]
+ Parameters
    + page (number) - An optional page number, default is 1

### Obtain a list of people. [GET]

+ Response 200 (application/json)

        {
            "people": [
                {
                    "birth_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "country": "U.S.A.",
                    "death_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "deck": "A prolific American voice actress who has voiced many characters in several anime series and video games. She has also worked as an ADR Director and Line Producer.",
                    "games_created": 135,
                    "hometown": "Mississippi",
                    "id": 45059,
                    "image": null,
                    "name": "Laura Bailey"
                },
                {
                    "birth_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "country": "",
                    "death_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "deck": "Arjuna Ravikumar is a video game developer at Electronic Arts.",
                    "games_created": 15,
                    "hometown": "",
                    "id": 101112,
                    "image": null,
                    "name": "Arjuna Ravikumar"
                },
                {
                    "birth_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "country": "",
                    "death_date": "Mon, 01 Jan 1900 00:00:00 GMT",
                    "deck": "Julie is an actress who has been doing voices for video games since 2004.",
                    "games_created": 19,
                    "hometown": "",
                    "id": 92094,
                    "image": null,
                    "name": "Julie Nathanson"
                }
            ]
        }

## Person [/people/{person_id}]
+ Parameters
    + person_id (number) - ID of the person in the form of an integer

### Get the details of a specific person. [GET]
+ Response 200 (application/json)

        {
            "birth_date": "Mon, 01 Jan 1900 00:00:00 GMT",
            "country": "",
            "death_date": "Mon, 01 Jan 1900 00:00:00 GMT",
            "deck": "Worked on Gun: Showdown",
            "games": [
            {
              "id": 2227,
              "name": "Gun: Showdown"
            },
            {
              "id": 2502,
              "name": "Call of Duty 3"
            }
            ],
            "games_created": 2,
            "hometown": "",
            "id": 45,
            "image": null,
            "name": "Jonathan Menzies"
        }

# Group Games

## Game List [/games/{page}]
+ Parameters
    + page (number) - An optional page number, default is 1

### Obtain a list of games. [GET]
+ Response 200 (application/json)

        {
            "games": [
                {
                    "deck": "Monopoly Millionaire is an iOS game based on the Monopoly Millionaire board game.",
                    "developers": [
                        {
                            "id": 1,
                            "name": "Electronic Arts"
                        }
                    ],
                    "id": 1,
                    "image": "http://static.giantbomb.com/uploads/scale_medium/10/103881/2345937-monopoly_millionaire.jpg",
                    "name": "Monopoly Millionaire",
                    "platforms": [
                        {
                            "id": 83,
                            "name": "iPhone",
                            "short": "IPHN"
                        },
                        {
                            "id": 107,
                            "name": "iPad",
                            "short": "IPAD"
                        },
                        {
                            "id": 109,
                            "name": "Android",
                            "short": "ANDR"
                        }
                    ],
                    "publishers": [
                        {
                        "id": 1,
                        "name": "Electronic Arts"
                        }
                    ]
                },
                {
                "deck": "The Sims' modern setting is put aside for a medieval one for this standalone title in the popular life simulator franchise.",
                "developers": [
                    {
                        "id": 1,
                        "name": "Electronic Arts"
                    }
                ],
                "id": 2,
                "image": "http://static.giantbomb.com/uploads/scale_medium/3/30036/1777126-box_165433_hd.jpg",
                "name": "The Sims Medieval",
                "platforms": [
                    {
                        "id": 15,
                        "name": "Mac",
                        "short": "MAC"
                    },
                    {
                        "id": 81,
                        "name": "PC",
                        "short": "PC"
                    }
                ],
                "publishers": [
                    {
                        "id": 403,
                        "name": "EA Games"
                    }
                ]
                }
            ]
        }

## Game [/game/{game_id}]
+ Parameters
    + game_id (number) - ID of the game in the form of an integer

### Get the details of a specific game. [GET]
+ Response 200 (application/json)

        {
            "deck": "Skitch, bone out, and thrash your way to the top in this extreme combat sports racing game from Electronic Arts.",
            "developers": [
                {
                    "id": 1,
                    "name": "Electronic Arts"
                }
            ],
            "id": 76,
            "image": "http://static.giantbomb.com/uploads/scale_medium/9/93770/2374500-genesis_skitchin.jpg",
            "name": "Skitchin'",
            "platforms": [
                {
                    "id": 5,
                    "name": "Genesis",
                    "short": "GEN"
                }
            ],
            "publishers": [
                {
                "id": 1,
                "name": "Electronic Arts"
                }
            ]
        }
