version: "2"

# A Docker Compose file for common configuration between development and production environments

services:
  lb:
    # The load balancer container. Built from the lb/Dockerfile.
    container_name: ggm8_lb
    build: lb
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"

  app:
    # The app container. Built from the app/Dockerfile.
    build: app
    restart: unless-stopped
    networks:
      backend:
        aliases:
          # All app servers be referred to by this alias with the backend network
          - apps
    environment:
      # Environment variables to configure the app on startup.
      - POSTGRES_DB=postgres

  db:
    # The database container. Built from the db/Dockerfile.
    container_name: ggm8_db
    build: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      # Environment variables to configure postgres on startup.
      - POSTGRES_DB=postgres

  data:
    container_name: ggm8_db_data
    # The Data Volume Container used to mount a volume to store our persistent data
    # https://getcarina.com/docs/tutorials/data-volume-containers/
    image: cirros
    volumes:
      # Mount this path as a volume to store our MySQL files
      - /var/lib/postgres
    command: /bin/true
