version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: ggm8group/ggm8_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"

  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: ggm8group/ggm8_app
    expose:
      # Expose port 5000 so it's only visibile on the container, not the host
      - "5000"
    env_file: ggm8-postgres-prod.env
    command: gunicorn manage:app --bind 0.0.0.0:5000
      # Run Gunicorn to serve app requests

  db:
    extends:
      file: docker-compose-common.yml
      service: db
    image: ggm8group/ggm8_db
    expose:
      # Expose port 5432 so it's only visibile on the container, not the host
      - "5432"
    env_file:
      - ggm8-postgres-prod.env
    volumes_from:
      # Mount the volumes from the data container to store our MySQL files
      - data

  data:
    extends:
      file: docker-compose-common.yml
      service: data

networks:
  backend: {}